=== zeroknowledgediscovery/phantomdb/phase1/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "patient_id": {
        "type": "string"
      },
      "race": {
        "type": ["string", "null"]
      },
      "seeded": {
        "type": "boolean"
      },
      "DX_record": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "date": {
              "type": "string",
              "format": "date"
            },
            "code": {
              "type": "string"
            }
          },
          "required": ["date", "code"],
          "additionalProperties": false
        }
      }
    },
    "required": ["patient_id", "seeded", "DX_record"],
    "additionalProperties": false
  }
}

=== zeroknowledgediscovery/phantomdb/phase1/example.json
[
    {
        "patient_id": "NU126_00000",
        "DX_record": [
            {
                "date": "2010-09-11",
                "code": "E78.1"
            },
            {
                "date": "2011-09-08",
                "code": "E78.5"
            },
            {
                "date": "2014-02-20",
                "code": "E78.4"
            },
            {
                "date": "2018-07-28",
                "code": "E78.0"
            },
            {
                "date": "2015-02-20",
                "code": "Z12.3"
            },
            {
                "date": "2008-03-28",
                "code": "M54.1"
            },
            {
                "date": "2010-03-14",
                "code": "M54.1"
            },
            {
                "date": "2011-09-06",
                "code": "M54.1"
            },
            {
                "date": "2014-02-22",
                "code": "M54.8"
            },
            {
                "date": "2023-01-09",
                "code": "M54.5"
            },
            {
                "date": "2013-03-02",
                "code": "M25.5"
            },
            {
                "date": "2014-02-23",
                "code": "M25.5"
            },
            {
                "date": "2021-01-18",
                "code": "M25.5"
            },
            {
                "date": "2011-09-09",
                "code": "Z00.0"
            },
            {
                "date": "2017-02-06",
                "code": "Z00.0"
            },
            {
                "date": "2015-08-15",
                "code": "Z01.4"
            },
            {
                "date": "2019-07-25",
                "code": "Z01.8"
            },
            {
                "date": "2009-09-16",
                "code": "Z23"
            },
            {
                "date": "2018-02-01",
                "code": "Z23"
            },
            {
                "date": "2018-07-30",
                "code": "R10.8"
            },
            {
                "date": "2020-07-22",
                "code": "R10.8"
            },
            {
                "date": "2014-08-20",
                "code": "R06.0"
            },
            {
                "date": "2021-01-19",
                "code": "R06.0"
            },
            {
                "date": "2022-07-08",
                "code": "R06.0"
            },
            {
                "date": "2009-03-22",
                "code": "Z79.8"
            },
            {
                "date": "2021-07-18",
                "code": "Z79.4"
            },
            {
                "date": "2008-09-22",
                "code": "G47.3"
            },
            {
                "date": "2012-03-03",
                "code": "G47.3"
            },
            {
                "date": "2016-08-10",
                "code": "G47.3"
            },
            {
                "date": "2018-02-02",
                "code": "G47.0"
            },
            {
                "date": "2021-01-16",
                "code": "G47.3"
            },
            {
                "date": "2022-07-09",
                "code": "R53.8"
            },
            {
                "date": "2023-01-07",
                "code": "R53.1"
            },
            {
                "date": "2009-09-17",
                "code": "H25.1"
            },
            {
                "date": "2018-08-03",
                "code": "H25.1"
            },
            {
                "date": "2021-07-15",
                "code": "H25.1"
            },
            {
                "date": "2012-09-01",
                "code": "K21.9"
            },
            {
                "date": "2013-08-28",
                "code": "L82.0"
            },
            {
                "date": "2011-09-04",
                "code": "E66.3"
            },
            {
                "date": "2014-08-22",
                "code": "E66.3"
            },
            {
                "date": "2011-09-03",
                "code": "M51.3"
            },
            {
                "date": "2019-01-25",
                "code": "N39.0"
            },
            {
                "date": "2022-01-11",
                "code": "F41.9"
            },
            {
                "date": "2017-02-08",
                "code": "M19.9"
            },
            {
                "date": "2016-08-12",
                "code": "N95.2"
            },
            {
                "date": "2014-02-23",
                "code": "K57.3"
            },
            {
                "date": "2023-01-09",
                "code": "R73.0"
            },
            {
                "date": "2016-02-13",
                "code": "J20.9"
            },
            {
                "date": "2017-08-04",
                "code": "R94.3"
            },
            {
                "date": "2019-07-25",
                "code": "M47.8"
            },
            {
                "date": "2014-02-25",
                "code": "N40.1"
            },
            {
                "date": "2015-08-17",
                "code": "H35.3"
            },
            {
                "date": "2010-09-14",
                "code": "M75.2"
            },
            {
                "date": "2016-08-13",
                "code": "M75.1"
            },
            {
                "date": "2020-01-21",
                "code": "Z86.7"
            },
            {
                "date": "2018-07-30",
                "code": "Z51.8"
            },
            {
                "date": "2010-09-08",
                "code": "R00.1"
            },
            {
                "date": "2014-02-19",
                "code": "M62.8"
            },
            {
                "date": "2017-08-03",
                "code": "M62.8"
            },
            {
                "date": "2019-01-30",
                "code": "I49.9"
            },
            {
                "date": "2009-09-15",
                "code": "R51"
            },
            {
                "date": "2014-08-23",
                "code": "R51"
            },
            {
                "date": "2013-08-25",
                "code": "R31.1"
            },
            {
                "date": "2012-03-04",
                "code": "M50.3"
            },
            {
                "date": "2020-07-21",
                "code": "M50.9"
            },
            {
                "date": "2020-01-21",
                "code": "Z98.8"
            },
            {
                "date": "2020-01-22",
                "code": "C44.9"
            },
            {
                "date": "2013-02-28",
                "code": "M89.9"
            },
            {
                "date": "2018-07-28",
                "code": "M89.9"
            },
            {
                "date": "2009-03-18",
                "code": "M77.3"
            },
            {
                "date": "2022-07-12",
                "code": "H90.2"
            },
            {
                "date": "2015-02-18",
                "code": "L81.4"
            },
            {
                "date": "2019-01-27",
                "code": "M48.0"
            },
            {
                "date": "2008-03-23",
                "code": "E87.6"
            },
            {
                "date": "2010-09-11",
                "code": "I48.9"
            },
            {
                "date": "2011-03-09",
                "code": "H61.2"
            },
            {
                "date": "2011-03-10",
                "code": "R09.0"
            },
            {
                "date": "2019-07-27",
                "code": "R09.8"
            },
            {
                "date": "2016-08-08",
                "code": "K59.0"
            },
            {
                "date": "2011-09-08",
                "code": "R26.2"
            },
            {
                "date": "2013-02-28",
                "code": "R26.8"
            },
            {
                "date": "2021-07-13",
                "code": "R26.9"
            },
            {
                "date": "2021-01-15",
                "code": "R26.8"
            },
            {
                "date": "2013-02-27",
                "code": "I50.3"
            },
            {
                "date": "2020-01-21",
                "code": "N28.9"
            },
            {
                "date": "2009-09-15",
                "code": "N20.0"
            },
            {
                "date": "2017-08-06",
                "code": "I65.2"
            },
            {
                "date": "2014-08-24",
                "code": "D50.9"
            },
            {
                "date": "2012-03-03",
                "code": "R68.8"
            },
            {
                "date": "2019-07-26",
                "code": "R68.8"
            },
            {
                "date": "2009-03-20",
                "code": "R03.0"
            },
            {
                "date": "2010-03-13",
                "code": "R39.1"
            },
            {
                "date": "2013-02-28",
                "code": "D18.0"
            },
            {
                "date": "2011-03-07",
                "code": "R22.9"
            },
            {
                "date": "2021-01-16",
                "code": "H53.8"
            },
            {
                "date": "2018-01-31",
                "code": "M16.1"
            },
            {
                "date": "2017-08-07",
                "code": "Z95.5"
            },
            {
                "date": "2022-07-10",
                "code": "E88.0"
            },
            {
                "date": "2017-02-06",
                "code": "I83.9"
            },
            {
                "date": "2015-02-14",
                "code": "I67.8"
            },
            {
